# Generated by Django 3.2 on 2021-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_persian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='زمان پایان'),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='زمان آغاز'),
        ),
    ]
